# Generated by Django 4.0.5 on 2022-07-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rect_x', models.PositiveIntegerField(blank=True, null=True)),
                ('rect_y', models.PositiveIntegerField(blank=True, null=True)),
                ('rect_w', models.PositiveIntegerField(blank=True, null=True)),
                ('rect_h', models.PositiveIntegerField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('resize', models.BooleanField(default=False)),
                ('resize_width', models.PositiveIntegerField(blank=True, null=True)),
                ('resize_height', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
