# Generated by Django 4.0.6 on 2022-07-05 14:05

import core.utils.file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_image', models.ImageField(upload_to=core.utils.file.processed_upload_directory)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utils.file.default_upload_directory)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('related_img', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.processedimage')),
            ],
        ),
    ]
