# Generated by Django 4.0.6 on 2022-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processedimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
