# Generated by Django 4.1b1 on 2022-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_telegramdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_on',
            field=models.BooleanField(default=True, help_text='Control for processing img'),
        ),
    ]
