# Generated by Django 4.1rc1 on 2022-07-23 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_is_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 18, 6, 18, 997844, tzinfo=datetime.timezone.utc)),
        ),
    ]
